### ISSUE TITLE
Figure out a way to check & format smartсontracts

### ISSUE THREAD

**Issue by Arjentix** [hyperledger-iroha/iroha#3165]
Currently we check and format our WASM smartcontracts, triggers and validators inside our `build.rs` files. It's may be not the best place to do that, however it's working for us now, We would like to keep `build.rs` as simple as possible.

We can introduce new CI checks. We can introduce cargo makefile. Let's discuss it here.

Originally posted by @appetrosyan [here](https://github.com/hyperledger/iroha/pull/3106#discussion_r1104547490)

**Comment by Arjentix** [comment]
Also related to #3224

**Comment by mversic** [comment]
my 2 cents is that we shouldn't format any code in CI, this includes smart contracts. What we should do is only include a CI check that smart contracts are formatted
