### ISSUE TITLE
[suggestion] Re-evaluate deriving `serde` traits in `no_sd` contexts

### ISSUE THREAD

**Issue by QuentinI** [hyperledger-iroha/iroha#3407]
### Feature request

We probably have no need for `Serialize`/`Deserialize` in `no_std` contexts (triggers/validators).

### Motivation

> IMO, the Peer as a whole is an oversight if allowed on the smartcontract side: reason being that the Peer operations are registering and de-registering, which should be done rarely and with human oversight.

> Moreover, any form of serde deserialization has to do with running code in the peer, (not with the smartcontract) which usually depends on std. I don't think it's inconsistent, it's just not exactly what we're doing at the moment.

Originally by @appetrosyan in https://github.com/hyperledger/iroha/pull/3373#discussion_r1169629137

**Comment by mversic** [comment]
we should actually work on removing `no_std` support altogether from `data_model`
