### ISSUE TITLE
[BUG] Lack of Real-Time Transactions Display in Iroha 2 Events Pipeline

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger-iroha/iroha#3483]
### OS and Environment

MacOS, Docker Hub

### GIT commit hash

b1855454

### Minimum working example / Steps to reproduce

```bash
$  docker compose up -d    
$ ./iroha_client_cli events pipeline
$ ./iroha_client_cli domain register --id=dsfdf
```

### Actual result

The events pipeline does not display the passing transactions in real-time.
![image](https://github.com/hyperledger/iroha/assets/111361420/02705b8c-e3c0-45ad-b580-2b5ad8526317)

### Expected result

The events pipeline should output all the events related to Iroha 2 in real-time

### Who can help to reproduce?

@astrokov7

**Comment by appetrosyan** [comment]
We should investigate if this is true of all peers, or just one. It's possible that the event isn't ready by the time it's supposed to be emitted. 

We should also supplement (and leave in) some logs to see the process through. Pipeline events don't happent frequently and the extra diagnostics are worth the performance trade-off IMO.
