### ISSUE TITLE
Failing test in `iroha_crypto`

### ISSUE THREAD

**Issue by mversic** [hyperledger-iroha/iroha#4307]
Find out why this tests fails sometimes:

---- signature::secp256k1::test::secp256k1_sign stdout ----
thread 'signature::secp256k1::test::secp256k1_sign' panicked at crypto/src/signature/secp256k1.rs:259:78:
called `Result::unwrap()` on an `Err` value: Signing("signature::Error { source: None }")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by nxsaken** [comment]
Fixed in #4404
