### ISSUE TITLE
`CommittedTransaction::error` is not part of the block hash

### ISSUE THREAD

**Issue by mversic** [hyperledger-iroha/iroha#5001]
Since `CommittedTransaction::error` is not protected by the block hash why keep it in the block? 
Every block replays all transactions and determines whether transaction is correct or faulty

If we keep it in the block, should we (during consensus voting) reject those blocks that have it set to an incorrect value?

**Comment by mversic** [comment]
It's worth pointing out that `CommittedTransaction::error` also isn't protected with block signature

**Comment by mversic** [comment]
while this doesn't affect consensus or integrity of the blockchain, client that receives a block can't ever be certain that this value is correct

**Comment by mversic** [comment]
while this doesn't affect consensus or integrity of the blockchain, client that receives a block can't ever be certain that this value is correct

**Comment by mversic** [comment]
IMO we should keep `CommittedTransaction::error` separate from the block but make sure we return it to clients on `FindBlocks` query and block stream. Nodes themselves have no use for it

**Comment by Erigara** [comment]
> If we keep it in the block, should we (during consensus voting) reject those blocks that have it set to an incorrect value?

We already do that when validating transactions.

**Comment by mversic** [comment]
> > If we keep it in the block, should we (during consensus voting) reject those blocks that have it set to an incorrect value?
> 
> We already do that when validating transactions.

Yes, but we shouldn't. If the value is wrong, just correct it and use the block
